# Generated by Django 5.2.3 on 2025-06-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('nome', models.CharField(help_text='Nome completo do contato', max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(help_text='E-mail do contato', max_length=100)),
                ('telefone', models.CharField(help_text='Telefone do contato', max_length=11)),
                ('melhor_hora_para_contato', models.CharField(help_text='Melhor hora para contato do cliente', max_length=10)),
                ('mensagem', models.CharField(help_text='Text com a mensagem a ser enviada ao SAC da empresa', max_length=1024)),
            ],
        ),
    ]
