# Generated by Django 5.2.3 on 2025-06-23 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_alter_venda_datavenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='dataVenda',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 23, 23, 8, 16, 586995, tzinfo=datetime.timezone.utc), help_text='data da venda', null=True),
        ),
    ]
