# Generated by Django 5.2.3 on 2025-06-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='fornecedoresCodigo',
            new_name='fabricantesCodigo',
        ),
    ]
