# Generated by Django 5.2.3 on 2025-06-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('codigo', models.AutoField(help_text='Codigo do fornecedor', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do fornecedor', max_length=70)),
            ],
        ),
    ]
